### ISSUE TITLE
Problem in version 1.1.0 when running as support for Cucumber.js

### ISSUE THREAD

**Issue by karinepires** [Adezandee/cucumber-mink#55]
Hello,

First I would like to thank you for this project.
The error I'm encountering in cucumber-mink version 1.1.0 is:

```
$  ./node_modules/.bin/cucumberjs -r ./phantom.js 
/Users/karine/Projects/testing/phantom.js:16
  Mink.init(this, parameters);
       ^

TypeError: Mink.init is not a function
    at Object.module.exports (/Users/karine/Projects/testing/phantom.js:16:8)
    at /Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:65:25
    at Array.forEach (native)
    at Object.wrapper (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
    at Object.initializer (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:24:41)
    at Object.Library (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/support_code/library.js:122:25)
    at Object.getSupportCodeLibrary (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:10:58)
    at Object.getSupportCodeLibrary (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/cli/configuration.js:128:32)
    at Object.getSupportCodeLibrary (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/runtime.js:43:46)
    at Object.start (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/runtime.js:12:37)
    at Object.run (/Users/karine/Projects/testing/node_modules/cucumber/lib/cucumber/cli.js:60:15)
    at Object.<anonymous> (/Users/karine/Projects/testing/node_modules/cucumber/bin/cucumber.js:4:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

My phantom.js file is (and works fine with previous version of cucumber-mink):

```
var Mink = require('cucumber-mink');

// Phantomjs - GhostDriver
const parameters = {
  driver: {
    screenshotPath: 'test/',
    desiredCapabilities: {
      browserName: 'phantomjs',
    },
    logLevel: 'silent',
    port: 8910,
  },
};

module.exports = function () {
  Mink.init(this, parameters);
}
```

The cucumberjs version is 0.9.5

**Comment by Adezandee** [comment]
Hi @karinepires, seems like I made a mistake with ES6 module loading / ES5 nodejs require().
Quick fix: use `var Mink = require('cucumber-mink').default;`

Sorry for that, I'll make it right asap

**Comment by Adezandee** [comment]
@karinepires, ok fixed with 1.1.1 :+1: 
Thanks for your feedback !

**Comment by karinepires** [comment]
Hello! Thanks for the fast answer and correction!

However I'm still not able to run cucumber-mink.
I've tried to debug it but could not find anything. 
I've created some dockerfiles ([available here](https://github.com/karinepires/docker-test-cucumber-mink)) for testing it in a isolated environment to make sure was not something on my machine.

Using the client I get the following error:

```
Error: Window handle/name '[object%20Object]' is invalid (closed?)
    at new RuntimeError (/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/node_modules/webdriverio/build/lib/utils/RequestHandler.js:222:36)
    at Request.self.callback (/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/node_modules/webdriverio/node_modules/request/request.js:1318:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/node_modules/webdriverio/node_modules/request/request.js:1266:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

And using as cucumber support it does not run any steps. I just get zero output from cucumber and the same error as above on phantomjs.

**Comment by Adezandee** [comment]
Hi @karinepires, I've experienced many issues with phantomjs lately too. I'll have a try with your dockerfiles thanks for that. In the meantime, I recommend you use Firefox / Chrome headless drivers as their javascript engines are not terribly outdated like phantomjs
